import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          I am the Header
          <nav>
            <Link href="/about">About</Link>
            <Link href="/posts/1">Post 1</Link>
          </nav>
        </header>
        {children}
        <footer>I am the Footer</footer>
      </body>
    </html>
  );
}
